#! /bin/sh

#Load Key Bindings
pgrep -x sxhkd > /dev/null || sxhkd &

#Load Compositor
picom &

#Load Wallpaper
feh  --bg-fill ~/.dotfiles/wallpapers/wallpaper.jpg &

#Load Workspaces
bspc monitor -d I II III IV V 

#Binary Space Partition Window Manager Settings

#Set Border Width
bspc config border_width        1

#Set Border Height
bspc comfig border_height	    1

#Set Window Gap
bspc config window_gap          2

#Split Ratio, Master Window always a bit bigger becuase it's pretty
bspc config split_ratio          0.65

#Launch Polybar
$HOME/.config/polybar/launch.sh
