#! /bin/sh

#Load Key Bindings
pgrep -x sxhkd > /dev/null || sxhkd &

#Load Compositor
picom &

#Load Wallpaper
feh  --bg-fill ~/.dotfiles/wallpapers/wallpaper.jpg &

#Determine if there is an external Monitor Connected
if [[ $(xrandr -q | grep -w  "HDMI1 connected") ]]; 
then
	
	#Load Workspaces across Multiple Monitors
	bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 
	bspc monitor LVDS1 -d 0

else

	bspc monitor LVDS1  -d 1 2 3 4 5 6 7 8 9 0

fi

#Binary Space Partition Window Manager Settings

#Set Border Width
bspc config border_width        1

#Set Border Height
bspc comfig border_height	    1

#Set Window Gap
bspc config window_gap          2

#Split Ratio, Master Window always a bit bigger becuase it's pretty
bspc config split_ratio         0.55

#Launch the Battery Warning Script
$HOME/.dotfiles/bin/battery_alert &

#Launch Polybar
$HOME/.config/polybar/launch.sh &
